nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ["http://localhost:5173"]
        allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link"]
        max_age: 3600
        allow_credentials: false

    paths:
        "^/api/":
            allow_origin: ["http://localhost:5173"]
            allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
            allow_headers: ["Content-Type", "Authorization"]
            max_age: 3600
            allow_credentials: false
